version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_vendi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vendi:
    build: .
    container_name: vendi_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"

volumes:
  mysql_data: