#profiles
ACTIVE_PROFILE: dev
APPLICATION_NAME: vendi

#database
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: vendi
MYSQL_USERNAME: root
MYSQL_PASSWORD: root

#server
CONTAINER_PORT: 8080

#email
EMAIL_USERNAME: k.glazer2003@gmail.com
EMAIL_PASSWORD: kfju nhwa piyh ymoe
